// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwuymwbtxkijpubsfijd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3dXltd2J0eGtpanB1YnNmaWpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwODc2MzMsImV4cCI6MjA2NTY2MzYzM30.zK5V6og5hPMkeVdKJsk89TU4OB_-MzUFnKZe_KwAuQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);